name: C/C++ CI

on:
  push:
    branches: 
      - '**'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get install -y valgrind

    - name: Build for testing
      run: make test

    - name: Test with valgrind
      run: make valgrind

    - name: Clean up
      run: make clean
